apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pad
  namespace: pad
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: pad.ddns.net
      http:
        paths:
          - backend:
              service:
                name: pad
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific